language: node_js
node_js:
- stable
before_install:
- npm install -g npm@latest
before_deploy:
- npm run-script build
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: UDFgPtImLbz7dfoVTRuZ2xXMSMCbMNe31ImsWqUeV4ECYWzCGPEXZSV56qar4+jgD2noCvy+SzB/B3+QgFPG+zeKP/3WJ7nFlALP82mIgLExPpEakVtXlYO517d/4pyF5erO/yicP+3oC0iHZKPk/zSqoWj2MB9NWkQbYhJSbcsIjWG7z2zZQ0Zk9sELFR+pUn7vOrWg0y7rlzDil3AynsRneL0ryihCjYvCIlqc6SeuroLvNKjHww9Ca8z5l4mPVDrOzELxbVwN6wD+IOpzW7/Pe9VX0FVFhH3sdrDiVY0Yf//xDs4abiSNcFH+B0KnMMFHiPWRGBPG1uKYZbTWTefAAAnaLOkzTkbGyv62Cxwbz1AVMdYvqVr7tCPQrNEbYdWEkKKquUkz4NeDiBIRTxj/bmoA79JH1kXu3Ja+yCl0oUW7BioDKZn7hdSuWp0iPpiyAhP37BbsyX8NrYMqD6oeHElrdI31JQx/kfOYxsjZIV7R6UrdJgGbEAVLdtN4p8JdUPid594m0JDaoGeGMdN77rWugwkmxeztbwaxIW13R9xHCppMBs0Yrhz/3M9/AC95gmUxBbcN7F1xiBFLAHbILne5si6e2Zm+MZ/BsU+NtPmIrBYDuDP3esENJs1785ySzHyB2uywSGL4qy335u0zuEbjwrt6FWfsVdhipLo=
  app: devmunch-dev
  on:
    repo: jondam1985/devmunch
    branch: dev/main
